application: praxis-market
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /
  script: helloworld.application

- url: /website/(.+)
  static_files: website/\1
  upload: website/(.*)

- url: /website/
  static_files: website/index.html
  upload: website/index.html

skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - ^\.git/.*
  - \.*\.lint$
  - ^fabfile\.py
  - ^testrunner\.py
  - ^grunt\.js
  - ^node_modules/(.*/)?